[
  "Success",
  "Unknown HCI Command",
  "Unknown Connection Identifier",
  "Hardware Failure",
  "Page Timeout",
  "Authentication Failure",
  "PIN or Key Missing",
  "Memory Capacity Exceeded",
  "Connection Timeout",
  "Connection Limit Exceeded",
  "Synchronous Connection Limit to a Device Exceeded",
  "ACL Connection Already Exists",
  "Command Disallowed",
  "Connection Rejected due to Limited Resources",
  "Connection Rejected due to Security Reasons",
  "Connection Rejected due to Unacceptable BD_ADDR",
  "Connection Accept Timeout Exceeded",
  "Unsupported Feature or Parameter Value",
  "Invalid HCI Command Parameters",
  "Remote User Terminated Connection",
  "Remote Device Terminated due to Low Resources",
  "Remote Device Terminated due to Power Off",
  "Connection Terminated By Local Host",
  "Repeated Attempts",
  "Pairing Not Allowed",
  "Unknown LMP PDU",
  "Unsupported Remote Feature / Unsupported LMP Feature",
  "SCO Offset Rejected",
  "SCO Interval Rejected",
  "SCO Air Mode Rejected",
  "Invalid LMP Parameters / Invalid LL Parameters",
  "Unspecified Error",
  "Unsupported LMP Parameter Value / Unsupported LL Parameter Value",
  "Role Change Not Allowed",
  "LMP Response Timeout / LL Response Timeout",
  "LMP Error Transaction Collision",
  "LMP PDU Not Allowed",
  "Encryption Mode Not Acceptable",
  "Link Key cannot be Changed",
  "Requested QoS Not Supported",
  "Instant Passed",
  "Pairing With Unit Key Not Supported",
  "Different Transaction Collision",
  "Reserved",
  "QoS Unacceptable Parameter",
  "QoS Rejected",
  "Channel Classification Not Supported",
  "Insufficient Security",
  "Parameter Out Of Manadatory Range",
  "Reserved",
  "Role Switch Pending",
  "Reserved",
  "Reserved Slot Violation",
  "Role Switch Failed",
  "Extended Inquiry Response Too Large",
  "Secure Simple Pairing Not Supported By Host",
  "Host Busy - Pairing",
  "Connection Rejected due to No Suitable Channel Found",
  "Controller Busy",
  "Unacceptable Connection Parameters" ,
  "Directed Advertising Timeout",
  "Connection Terminated due to MIC Failure",
  "Connection Failed to be Established",
  "MAC Connection Failed",
  "Coarse Clock Adjustment Rejected but Will Try to Adjust Using Clock Dragging"
]